### ISSUE TITLE
Demo is not running 

### ISSUE THREAD

**Issue by tonydspaniard** [openwallet-foundation/credo-ts#1520] opened 2023-07-22 15:49 UTC
Hi According to the error log is having an issue with the bindings. 

```
aries-framework-javascript/node_modules/bindings/bindings.js:126
  err = new Error(
        ^
Error: Could not locate the bindings file. Tried:
 → /Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/build/indynodejs.node
 → /Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/build/Debug/indynodejs.node
 → /Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/build/Release/indynodejs.node
 → /Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/out/Debug/indynodejs.node
 → /Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/Debug/indynodejs.node
 → /Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/out/Release/indynodejs.node
 → /Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/Release/indynodejs.node
 → /Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/build/default/indynodejs.node
 → /Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/compiled/16.17.1/darwin/arm64/indynodejs.node
 → /Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/addon-build/release/install-root/indynodejs.node
 → /Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/addon-build/debug/install-root/indynodejs.node
 → /Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/addon-build/default/install-root/indynodejs.node
 → /Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/lib/binding/node-v93-darwin-arm64/indynodejs.node
    at bindings (/Users/{none}/Documents/aries-framework-javascript/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/src/indyBinding.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require.extensions.<computed> [as .js] (/Users/{none}/Documents/aries-framework-javascript/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/src/index.js:1:14) {
  tries: [
    '/Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/build/indynodejs.node',
    '/Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/build/Debug/indynodejs.node',
    '/Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/build/Release/indynodejs.node',
    '/Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/out/Debug/indynodejs.node',
    '/Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/Debug/indynodejs.node',
    '/Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/out/Release/indynodejs.node',
    '/Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/Release/indynodejs.node',
    '/Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/build/default/indynodejs.node',
    '/Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/compiled/16.17.1/darwin/arm64/indynodejs.node',
    '/Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/addon-build/release/install-root/indynodejs.node',
    '/Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/addon-build/debug/install-root/indynodejs.node',
    '/Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/addon-build/default/install-root/indynodejs.node',
    '/Users/{none}/Documents/aries-framework-javascript/node_modules/indy-sdk/lib/binding/node-v93-darwin-arm64/indynodejs.node'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

What am I missing? Do I need to install something else? Nothing found on the docs... Do i need to install other resources? 

Maybe the demo is old, maybe I need to modify something within (i.e. Askar instead of indy-sdk). 

Thank you very much in advance

**Comment by genaris** [comment] 2023-07-22 17:36
Are you running the demo from the main branch? If that's the case, it seems to me a bit weird since the demo is already using Askar instead of Indy SDK.

**Comment by bugamehmet** [comment] 2023-07-22 19:02
The error you're encountering is related to missing bindings for the indy-sdk library. Make sure you've installed all the dependencies using npm install or yarn. Check for updates and compatibility with other modules used in Aries framework.

**Comment by mmatteo23** [comment] 2023-07-25 16:52
Hi, also found problems here.

I pulled your repo and then run Faber and Alice using `yarn faber` and `yarn alice` in two terminals and the connection attempt goes into timeout every time.
So I opened the code and tried to increase the timeout and this happened:

![timeout_but_enstablished](https://github.com/hyperledger/aries-framework-javascript/assets/75645114/fbb5c6cf-3813-45db-a4fe-64f42050f24e)

So Alice says "Connection established!" and Faber seems to have gone into error showing "Timeout of 20 seconds reached.. Returning to home screen.". Someone lies!

I tried also to launch the "Offer credential" and something very similar happens because Faber goes into error saying `MessageSendingError: Message is undeliverable to connection d4b83b78-e99c-46cf-b2b4-fffd20086636 (alice)` and when it stops Alice receives the credential offer showing the question where you have to decide if you want to accept or deny the credential.

**Comment by genaris** [comment] 2023-07-25 17:49
> Hi, also found problems here.
> 
> I pulled your repo and then run Faber and Alice using `yarn faber` and `yarn alice` in two terminals and the connection attempt goes into timeout every time. So I opened the code and tried to increase the timeout and this happened:
> 
> 
> So Alice says "Connection established!" and Faber seems to have gone into error showing "Timeout of 20 seconds reached.. Returning to home screen.". Someone lies!
> 

Still not sure what's going on with @tonydspaniard issue but in your case I think it's the same problem than https://github.com/hyperledger/aries-framework-javascript/issues/1452. You should be able to fix it by using the patched ref-napi. Hopefully we'll be able to solve all these confusing issues as soon as we can drop support to node 16, so we can safely use it by default.

**Comment by mmatteo23** [comment] 2023-07-26 10:47
Hi @genaris thank you for your answer.

Anyway, I also tried to add your suggested fix:
```json
"resolutions": {
    "@types/node": "^16.11.7",
    "ref-napi": "npm:@2060.io/ref-napi"
  },
```

but nothing changed 😢, I also added a very high value for the timeout.

From agents' loggers (by setting up `new ConsoleLogger(LogLevel.debug)`) seems like Alice and Faber can communicate but their internal computation is too slow and they fail each connection attempt.

Let me report the logs:
**Alice** after pasting the invitation link:
```
DEBUG: Sending outbound message to service: {
  "messageId": "be6bf4b2-d4ad-45a9-970d-b470311e68f1",
  "service": {
    "id": "#inline-0",
    "recipientKeys": "omitted...",
    "routingKeys": "omitted...",
    "serviceEndpoint": "http://localhost:9001"
  }
}
DEBUG: Pack outbound message https://didcomm.org/didexchange/1.0/request
DEBUG: Sending outbound message to endpoint 'http://localhost:9001
DEBUG: No response received.
```
After the last Alice's log, Faber started to log something among which:
```
DEBUG: Sending outbound message to service: {
  "messageId": "5439d4d0-dfb1-4d89-b739-dd68a6972e7d",
  "service": {
    "id": "#inline-0",
    "recipientKeys": "omitted...",
    "routingKeys": "omitted...",
    "serviceEndpoint": "http://localhost:9000"
  }
}
DEBUG: Pack outbound message https://didcomm.org/didexchange/1.0/response
DEBUG: Sending outbound message to endpoint 'http://localhost:9000'
ERROR: Error sending message to http://localhost:9000: The user aborted a request.
```

And in fact, Faber says that Alice has aborted the request (IMO because it responded too late).

Have you got any ideas? I can also provide a screen recording if that would be helpful

**Comment by genaris** [comment] 2023-07-26 11:30
After changing package json you need to re-run yarn install.

If you don't see any change, you may need to delete node_modules directory and run yarn install again.

**Comment by mmatteo23** [comment] 2023-07-26 14:42
Yes, I did exactly that. I both did just `yarn install` and reinstalled the dependencies by deleting the `node_modules` directory.
Same errors and same behaviour.

**Comment by genaris** [comment] 2023-07-26 15:13
> Yes, I did exactly that. I both did just `yarn install` and reinstalled the dependencies by deleting the `node_modules` directory. Same errors and same behaviour.

That extremely slow computation issue you are describing is exactly what happens to us without the patched `ref-napi`.

Are you running node 18? Just to make sure the patched version is in place, could you check that `node_modules/ref-napi/package.json` is effectively showing `@2060.io/ref-napi` in its name field?

**Comment by mmatteo23** [comment] 2023-07-27 08:56
I checked that the name `node_modules/ref-napi/package.json` was indeed `@2060.io/ref-napi` and it was not. I deleted `node_modules` and the `yarn.lock` file again and this time the patch was set correctly.
Sorry, idk why it didn't work the previous time.

But I can confirm that the performance changes radically and it works.

**Comment by mmatteo23** [comment] 2023-07-27 08:58
Thank u @genaris 🫡

**Comment by sudddy** [comment] 2023-08-24 20:11
@tonydspaniard Did you fix the error ?

**Comment by sudddy** [comment] 2023-08-24 20:19
@genaris I'm facing the same issue.

**Comment by genaris** [comment] 2023-08-24 21:25
@tonydspaniard @sudddy in the trace I see the following line:
```
ld: library not found for -lindy
```

It indicates that you don't have libindy in your system. Even if it is not required for running the demo, it is a dependency on the root repository (this is something we want to fix shortly).

For the time being, I think you can fix your problem by installing Indy SDK, something quite straightforward to do under MacOS: you just need to follow the guide for [ARM](https://aries.js.org/guides/0.4/getting-started/set-up/indy-sdk/macos-arm) processors (@tonydspaniard  case) or [Intel](https://aries.js.org/guides/0.4/getting-started/set-up/indy-sdk/macos-intel) processors

**Comment by TimoGlastra** [comment] 2024-02-14 06:05
Indy SDK has been removed. Closing issue

**Closed by TimoGlastra** 2024-02-14 06:05 UTC
