### ISSUE TITLE
npx -p @aries-framework/node@^0.3 is-indy-installed

### ISSUE THREAD

**Issue by dnaicker86** [openwallet-foundation/credo-ts#1619] opened 2023-10-31 09:14 UTC
Following the tutorial on https://aries.js.org/guides/0.4/getting-started/set-up/indy-sdk/windows

After running `npx -p @aries-framework/node@^0.3 is-indy-installed` it does not confirm whether indy is installed but rather re-installs it.

Should this command say a yes/no for installation found?

I ensured the env var path is set for:
![image](https://github.com/hyperledger/aries-framework-javascript/assets/130728803/f57a3a9b-40b4-45bf-bc1e-9a30f3a9d8f6)
and the library folder is unzipped

```
denai@Denver MINGW64 ~
$ npx -p @aries-framework/node@^0.3 is-indy-installed
Need to install the following packages:
@aries-framework/node@0.3.3
Ok to proceed? (y) y
npm WARN deprecated @babel/plugin-proposal-numeric-separator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
npm WARN deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
npm WARN deprecated @babel/plugin-proposal-optional-catch-binding@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm WARN deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated @babel/plugin-proposal-async-generator-functions@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
npm WARN deprecated @babel/plugin-proposal-export-namespace-from@7.18.9: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-export-namespace-from instead.
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
npm WARN deprecated @unimodules/core@7.1.2: replaced by the 'expo' package, learn more: https://blog.expo.dev/whats-new-in-expo-modules-infrastructure-7a7cdda81ebc
npm WARN deprecated @unimodules/react-native-adapter@6.3.9: replaced by the 'expo' package, learn more: https://blog.expo.dev/whats-new-in-expo-modules-infrastructure-7a7cdda81ebc
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\denai\\AppData\\Local\\npm-cache\\_npx\\b2013cfe335b6227\\node_modules\\@digitalcredentials',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\denai\AppData\Local\npm-cache\_npx\b2013cfe335b6227\node_modules\@digitalcredentials\jsonld-signatures'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\denai\\AppData\\Local\\npm-cache\\_npx\\b2013cfe335b6227\\node_modules\\@digitalcredentials\\jsonld-signatures'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\denai\\AppData\\Local\\npm-cache\\_npx\\b2013cfe335b6227\\node_modules\\react-native',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\denai\AppData\Local\npm-cache\_npx\b2013cfe335b6227\node_modules\react-native\ReactAndroid\src\main\java\com'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\denai\\AppData\\Local\\npm-cache\\_npx\\b2013cfe335b6227\\node_modules\\react-native\\ReactAndroid\\src\\main\\java\\com'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\denai\\AppData\\Local\\npm-cache\\_npx\\b2013cfe335b6227\\node_modules\\react-native-securerandom',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\denai\AppData\Local\npm-cache\_npx\b2013cfe335b6227\node_modules\react-native-securerandom\android\build\generated'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\denai\\AppData\\Local\\npm-cache\\_npx\\b2013cfe335b6227\\node_modules\\react-native-securerandom\\android\\build\\generated'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]

denai@Denver MINGW64 ~
$ npx -p @aries-framework/node@^0.3 is-indy-installed
Need to install the following packages:
@aries-framework/node@0.3.3
Ok to proceed? (y) npm ERR! canceled

npm ERR! A complete log of this run can be found in: C:\Users\denai\AppData\Local\npm-cache\_logs\2023-10-31T09_11_17_581Z-debug-0.log

denai@Denver MINGW64 ~
$
```

using windows 11, git bash, node version 18

**Comment by berendsliedrecht** [comment] 2023-11-02 10:07
I am not sure what the issue is. the `is-indy-installed` does not reinstall libindy. It calls a function from the nodejs wrapper to see if `libindy` (not `indy-sdk` on node.js) is installed on your machine.

**Comment by TimoGlastra** [comment] 2024-02-14 05:54
Indy SDK has been deprected in 0.4 and removed in 0.5. Closing

**Closed by TimoGlastra** 2024-02-14 05:54 UTC
