### ISSUE TITLE
Unable to Establish Connection Between Base Agents After Adding Tenants Module

### ISSUE THREAD

**Issue by tarun-vadde** [openwallet-foundation/credo-ts#1501] opened 2023-07-08 07:05 UTC
## Overview
I am encountering an issue when attempting to establish a connection between two different base agents after integrating the Tenants module in my implementation of the AFJ (Aries Framework JavaScript) version 0.4.0. This issue arises while initializing an agent using the provided configuration.

## Steps to Reproduce
To reproduce the issue, follow these steps:

- Use AFJ version 0.4.0 in the @aries-framework/core and @aries-framework/tenants packages.
- Initialize an agent with the following configuration:

```
const agent1 = new Agent({
  config: agent1Config,
  modules: {
    tenants: new TenantsModule(),
    indySdk: new IndySdkModule({ indySdk }),
    connections: new ConnectionsModule({
      autoAcceptConnections: true,
    }),
  },
  dependencies: agentDependencies,
});
```

- Attempt to establish a connection between two different base agents.

## Expected Behavior
I expect the connection between the two base agents to be successfully established, allowing for further interaction and communication.

## Observed Behavior
Instead, I am encountering the following error:

`Error: Couldn't determine tenant id for inbound message. Unable to create context.`

This error prevents the successful establishment of the connection.

## Additional Information
I have ensured that all required dependencies and configurations are properly set up. Prior to integrating the Tenants module, I did not experience any issues with establishing connections between base agents.

## Environment
@aries-framework/core Version: 0.4.0
@aries-framework/tenants Version: 0.4.0
Node.js Version: v16.19.1
Operating System: Ubuntu 18.04.6 LTS Bionic

## Possible Solution
I have attempted to troubleshoot this issue by reviewing the documentation and searching for related discussions, but have not been able to identify a solution. I suspect there may be a misconfiguration or a missing step in setting up the Tenants module or its dependencies.

## Impact
This issue prevents me from establishing connections between base agents, which is a critical functionality required for my project. Resolving this issue is crucial to proceed with the development and deployment of my application.

I appreciate any assistance or guidance in resolving this issue.

**Comment by blu3beri** [comment] 2023-07-10 15:34
Do you have a full reproducible repository to recreate this issue? "establishing a connection between two base agents" can be done in many ways

**Comment by tarunvadde** [comment] 2023-07-10 20:32
Yes, but I'm looking for a solution to this particular issue of why is it that I am not able to establish a connection between two different agents if I am using `new Tenants()` module while initializing the agent.

Or please let me know where I'm doing wrong. 

`Error: Couldn't determine tenant id for inbound message. Unable to create context.
`

**Comment by tarunvadde** [comment] 2023-07-10 20:32
> Do you have a full reproducible repository to recreate this issue? "establishing a connection between two base agents" can be done in many ways
Yes, but I'm looking for a solution to this particular issue of why is it that I am not able to establish a connection between two different agents if I am using `new Tenants()` module while initializing the agent.

Or please let me know where I'm doing wrong. 

`Error: Couldn't determine tenant id for inbound message. Unable to create context.
`

**Comment by tarun-vadde** [comment] 2023-07-11 07:03
> Do you have a full reproducible repository to recreate this issue? "establishing a connection between two base agents" can be done in many ways

Yes, but I'm looking for a solution to this particular issue of why I cannot establish a connection between two different agents if I am using the `new Tenants()` module while initializing the agent.

Or please let me know what I'm doing wrong.

`Error: Couldn't determine tenant id for inbound message. Unable to create context. `

**Comment by blu3beri** [comment] 2023-07-11 07:06
I know. But without a reproduction environment it is impossible for us to solve. The error and use case are too vague to find the root cause.

**Comment by TimoGlastra** [comment] 2024-02-14 06:26
Closing as a lot has changed. If the issue still persists with latest 0.5.0 alphla, node 18/20 and 0.2.0 of the shared components, please open a new issue. Thanks!

**Closed by TimoGlastra** 2024-02-14 06:26 UTC
