### ISSUE TITLE
Error deleting AnonCreds credentials after upgrading from 0.4.2 to 0.5.3

### ISSUE THREAD

**Issue by bryce-mcmath** [openwallet-foundation/credo-ts#1882] opened 2024-05-27 23:40 UTC
Credo raises an error when attempting to delete a credential in 0.5.3 that was received in 0.4.2

Error originates in @credo-ts/anoncreds V1CredentialProtocol.ts
`[CredoError: Unsupported credential record type anoncreds for v1 issue credential protocol (need w3c)]`

This occurs when calling `agent.credentials.deleteById(credential.id)` from Bifold. I might be wrong but I believe we were using V1 protocol with AnonCreds in Credo/AFJ 0.4.2 so I'm confused why it appears to no longer be supported.

Of `credentialRecord.credentials` the `credentialRecord` part seems to be deleted successfully but not the `.credentials` part. I think, higher up in Credo, it's failing during 'deleting associated credentials' loop [here](https://github.com/openwallet-foundation/credo-ts/blob/dcb363dc7e7abbbcce8b3a344a487a186eb5c88e/packages/core/src/modules/credentials/protocol/BaseCredentialProtocol.ts#L257)

Thank you for any help and let me know if I can provide more info or assist in any way

**Comment by genaris** [comment] 2024-05-28 12:36
Looking at the error you got, it looks like the credential exchange record was not properly migrated, so it is still bound to an anoncreds credential record instead of a w3c one. 

It's a bit weird because this was fixed in https://github.com/openwallet-foundation/credo-ts/pull/1849, just before 0.5.3 was released. Actually, we did that fix right after @wadeking98 reported the very same issue on [Discord](https://discord.com/channels/1022962884864643214/1179453305856991263/1234618054726516738). 

Are you upgrading from 0.4.2 to 0.5.3 directly or did you pass by 0.5.0/0.5.1/0.5.2 in the middle?

**Comment by wadeking98** [comment] 2024-05-30 00:53
I'm able to reproduce this too, funny I thought it was fixed but maybe I was mistaken

**Comment by bryce-mcmath** [comment] 2024-05-30 16:59
@genaris @TimoGlastra any ideas? Any way we can help with this one?

**Comment by genaris** [comment] 2024-05-30 20:17
> @genaris @TimoGlastra any ideas? Any way we can help with this one?

Could you give me some pointers to reproduce this issue easily? I've reproduced an upgrade from 0.4.2 to 0.5.3 with two credential exchanges: an Indy credential received with Issue Credential V1 protocol (taken from https://demo.animo.id) and a newer AnonCreds with Issue Credential V2 protocol (from 2060 chatbot demos) and both were succesfully found and updated to have the bindings to the w3c record.

I've tried also with BC Showcase but for some reason it is not working with [Hologram app](https://2060.io/hologram/): it sends an 'abandoned' error when I request the credential. Weird, since it used to work fine not so long ago.

**Comment by bryce-mcmath** [comment] 2024-05-30 20:29
I believe in this case (and in most of our ecosystem) it's all AnonCreds but with V1, so if you could try that combo hopefully you'll be able to repro.

@wadeking98 possible Traction issue with the showcase?

**Comment by bryce-mcmath** [comment] 2024-05-30 20:32
For us to repro it, we basically install the last AFJ 0.4.2 version of Bifold or BC Wallet, get a credential from the showcase, and then upgrade to our latest development build (0.5.3) and attempt to delete the credential.

**Comment by wadeking98** [comment] 2024-05-31 18:43
@genaris running into an issue with the student showcase credential, try the lawyer/person credentials in the showcase

**Comment by genaris** [comment] 2024-06-02 01:51
> @genaris running into an issue with the student showcase credential, try the lawyer/person credentials in the showcase

Allright, so I could reproduce it by installing the tagged v1.0.16, receiving Lawyer and Person credentials, and then switching to `main`. After the fix in https://github.com/openwallet-foundation/credo-ts/pull/1887 it seems to work properly (I tested presenting the credentials and the deleting them).

I'll leverage all this environment setup to check also the Mobile Verifier issue that raised https://github.com/hyperledger/anoncreds-rs/pull/335. Hopefully we can get some proposal to fix it during next week. You are more than welcome to participate in next Credo contributor meeting (Thursday June 6th), as we may have some good discussion about this topic!

**Closed** 2024-06-05 21:12 UTC
